export const TEAM_DETAIL = "TEAM_DETAIL";
export const SAVE_DATA = "SAVE_DATA";

export const OVER_DETAIL = "OVER_DETAIL";
export const GET_TEAM_DETAIL = "GET_TEAM_DETAIL";

export const SCORECARD = "SCORECARD";

export const INNING_DETAIL = "INNING_DETAIL";
export const FETCH_INNING_DETAIL = "FETCH_INNING_DETAIL";
export const SET_FETCHED_INNING_DETAIL = "SET_FETCHED_INNING_DETAIL";

export const UPDATE_INNING_DETAIL = "UPDATE_INNING_DETAIL";

export const STRIKE_CHANGE = "STRIKE_CHANGE";

export const INNING_END = "INNING_END";

export const SAVE_DATA_PER_OVER = "SAVE_DATA_PER_OVER";
export const INNING_DETAIL_FETCH = "INNING_DETAIL_FETCH";
export const SET_INNING = "SET_INNING";
